### ISSUE TITLE
Link error on x86 + MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [ned14/outcome#221] opened 2020-03-17 11:20 UTC
Hi all,

I use latest version of Outcome, Outcome failed due to link error on x86 build but passed on x64 on MSVC. I want to confirm does Outcome not support x86 build any more? Or it's a source issue? Thanks.

**build log:** [Outcome_x86_build.log](https://github.com/ned14/outcome/files/4343126/Outcome_build.log)

**error:**
MSVCRT.lib(exe_main.obj) : error LNK2019: unresolved external symbol _main referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ)
.\outcome_hl--issue0064-noexcept.exe : fatal error LNK1120: 1 unresolved externals

**Comment by ned14** [comment] 2020-03-17 14:24
Confirmed. It looks like the linker aliasing tricks to work around recent MSVCs refusing non-windows.h definitions of Windows function are x64-specific. Thanks for reporting the problem.

**Comment by ned14** [comment] 2020-03-18 10:48
I believe that this is now fixed. Thank you for reporting the problem!

**Closed by ned14** 2020-03-18 10:48 UTC
Labels: bug
