### ISSUE TITLE
Build fails with ninja generator

### ISSUE THREAD

**Issue by awvwgk** [ned14/outcome#265] opened 2022-07-01 12:33 UTC
Trying to configure outcome with `cmake -B _build -G Ninja -DCMAKE_BUILD_TYPE=Release` fails with

```
CMake Warning at _build/quickcpplib/repo/cmakelib/QuickCppLibUtils.cmake:84 (message):
  WARNING: .clang-tidy file found for project outcome, yet clang-tidy not on
  PATH so disabling lint pass
Call Stack (most recent call first):
  _build/quickcpplib/repo/cmakelib/QuickCppLibSetupProject.cmake:205 (indented_message)
  CMakeLists.txt:51 (include)


-- Missing dependency quickcpplib is NOT installed in cmake packages!
-- Missing dependency quickcpplib is NOT found at $SRC_DIR/_build/quickcpplib!
-- Superbuilding missing dependency quickcpplib with config Debug, this may take a while ...
CMake Error at _build/quickcpplib/repo/cmakelib/QuickCppLibUtils.cmake:95 (message):
  FATAL: Configure download, build and install of quickcpplib with
  -DCMAKE_BUILD_TYPE=Debug -G "Ninja" -DPROJECT_IS_DEPENDENCY=TRUE
  "-DQUICKCPPLIB_ROOT_BINARY_DIR=/home/conda/staged-recipes/build_artifacts/outcome-cpp_1656676380527/work/_build"
  failed with error '1'

  

  stdout was: -- Configuring incomplete, errors occurred!

  See also
  "/home/conda/staged-recipes/build_artifacts/outcome-cpp_1656676380527/work/_build/quickcpplib/CMakeFiles/CMakeOutput.log".


  

  

  stderr was: CMake Error: CMake was unable to find a build program
  corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You
  probably need to select a different build tool.

Call Stack (most recent call first):
  _build/quickcpplib/repo/cmakelib/QuickCppLibUtils.cmake:277 (checked_execute_process)
  _build/quickcpplib/repo/cmakelib/QuickCppLibUtils.cmake:371 (download_build_install)
  CMakeLists.txt:84 (find_quickcpplib_library)
```

It seems like the generator, in this case ninja is not communicated correctly. Using ninja would be useful for usage on Windows.

**Comment by ned14** [comment] 2022-07-06 15:58
Outcome works just fine with the Ninja generator. I use it daily at work.

I suspect the issue here is Conda. See #266 and #267.

**Comment by BurningEnlightenment** [comment] 2023-06-30 07:00
Since this hasn't seen any activity in a while, I'm going ahead and close this. Feel free to reopen if further qualifying information comes up (e.g. a [reprex]).

[reprex]: https://stackoverflow.com/help/minimal-reproducible-example

**Closed by BurningEnlightenment** 2023-06-30 07:00 UTC
